### PR TITLE
Output css

### PR DESCRIPTION
**Pull request by aaharu**
`dist\vueHotelDatepicker.css` file has not included since `vue-hotel-datepicker@4.0.0-beta.10`.

also `vhd__datepicker__months`'s style has not seem to work properly since `4.0.0-beta.10`.

image

### CODE REVIEW

**Comment by matiasperrone** [comment]
I don't think this is the right approach. Already fixed in beta 14

**Comment by aaharu** [comment]
Okay.

But, `vhd__datepicker__months`'s problem still is not fixed in beta 14.
Would you mind testing it on smartphones?

**Comment by matiasperrone** [comment]
Please comment in the new issue

**Comment by matiasperrone** [comment]
@aaharu please comment in #258 so I can continue from there. Include which version are you reporting of iOS and some other browser version related information.

**Pull request closed without merging**
