### PR TITLE
Change events to kebab-case

### PR DESCRIPTION
**Pull request by SxDx**
Camelcase Events cant be used with in-Dom templates because browsers convert them all to
lowercase. Vue.js recommends to use kebab-case for events and props.

### CODE REVIEW

**Comment by krystalcampioni** [comment]
@SxDx thanks for the contribution, and sorry for taking so long to reply!
Could you please solve the conflicts so I can merge your PR and publish a new release? 😬

**Comment by amulchinock** [comment]
@krystalcampioni Apologies for butting in. Been looking through the PR- bit difficult to manage merge conflicts with files generated by build tools. Traditionally they wouldn't be included in version control.

Is there a reason this was done? (I'm sure there is, I'm just not familiar enough with your codebase (yet) to know why) :)

**Comment by krystalcampioni** [comment]
@amulchinock Good point! To be honest there was no good reason, apart from I totally missed it 😂 Just pushed an update to fix this now 👍

**Comment by amulchinock** [comment]
@SxDx If you can, could you merge the latest version with your PR, and resubmit. Hopefully this will remove the minified files, and allow a merge of your PR.

**Comment by ahallez** [comment]
The documentation still mentions the old event names.
Please update the documentation page to reflect the changed event names.

**Comment by krystalcampioni** [comment]
@ahallez please submit a pull request if you want this to be changed soon :)

**Pull request merged**
