### PR TITLE
feat(styles): add prefix and default to variables

### LINKED ISSUE #226: [4.x] .datepicker__month-day--last-day-selected CSS isn't consistent with .datepicker__month-day--selected
These 2 use `background: HEX`
```
.datepicker__month-day--first-day-selected,
.datepicker__month-day--last-day-selected {
    background: ...;
}
```

but this uses `background-color: RGB`
```
.datepicker__month-day--selected {
    background-color: ...;
}
```

Please use only 1 way, to be consistent.

* background-color vs background
* HEX vs RGB

Hex codes can have opacity too: https://alligator.io/css/hex-code-colors-alpha-values/#:~:text=Comparing%20Hex%20Code%2BAlpha%20Format%20to%20RGBA&text=255%2C%20256).,opaque%20the%20color%20will%20be.

### PR DESCRIPTION
**Pull request by superbiche**
This PR does a few things related to styles which seem necessary for the v4 release:  

- [x] Prefix all SCSS variables with `$vhd__` to avoid conflicts when project is used with other frameworks  
- [x] Use `!default` to allow overriding values by setting the variables prior to including styles   
- [x] Use `rgba()` for `.datepicker__month-day--first-day-selected` (fixes #226)  
- [x] Add wrapper to center content on demo page  
- [x] **Prefix all classes with `.vhd__` to avoid conflicts with other datepicker libraries**  
- [x] **Use relative units instead of `px`**  

I have been too busy to finish it earlier, I'll deal with the items left in the next few days.

### CODE REVIEW

**Comment by matiasperrone** [comment]
I revised the conflicts and solved!
The only issue that I've found is that the "disabledWeeksDays" is a enumeration of date's names instead of numbers relative to first day.

**Comment by superbiche** [comment]
> But that is not the objective of this PR

Yup, I guess we can keep this issue scoped to the todo list, but make an issue for the `disabledWeeksDays` and fix it before v4.0.0.

**Comment by matiasperrone** [comment]
I agree! 😀

**Comment by matiasperrone** [comment]
Some extra testing is necessary. I didn't have the time to finish testing the last bullet.

**Comment by superbiche** [comment]
@matiasperrone this is HUGE! Thanks so much! I'll take some time tomorrow to test this :+1:

**Comment by matiasperrone** [comment]
Some extra variables were introduced. But I wasn't able to solve the border of "today".

Some weird issue happens with the number when selected and hover, and out... probably some decimal error...

**Comment by matiasperrone** [comment]
The testing area is nicer also 😁

**Comment by matiasperrone** [comment]
And then before going out with the Final Release we have to be able to launch a new doc https://krystalcampioni.github.io/vue-hotel-datepicker/#moreExamples

Is the "gh-pages" branch

**Comment by matiasperrone** [comment]
I think that I have an idea but note sure yet.

**Review by matiasperrone — APPROVED** [review]

**Comment by superbiche** [comment]
:tada:

**Pull request merged**
