### PR TITLE
fix: relative imports,i18n docs & defaults,prop mutation

### PR DESCRIPTION
**Pull request by superbiche**

### CODE REVIEW

**Comment by superbiche** [comment]
I have also updated the docs with new i18n strings, updated `i18n.js` with these new strings, and replaced the `defaultI18n` constant in `index.vue` by importing `i18n.js`.  
README updated according to this. Also, I thought using double quotes for keys & values would make it easier for folks using Vue-i18n with JSON translation files (otherwise, your IDE should replace those quickly).

Let me know what you think

**Comment by superbiche** [comment]
Fix a prop mutation in createHalfDayDates

**Comment by matiasperrone** [comment]
Let me check this out and I'll merge it.

**Review by matiasperrone — CHANGES_REQUESTED** [review]
- References to other components must use "~"
- `.npmrc` undelete the line 2

Please make this changes in order to merge please.

**Comment by superbiche** [comment]
@matiasperrone my answers to this :  

* `~` references are not resolved when using the source version of the package. These are only resolved during development, I don't think it's a good thing to break the possibility to use the `src` version of the package when installed.  

* Line 2 of .npmrc was 1/ commented out but .npmrc doesn't support comments, and 2/ was blocking npm install, build, and everything. Referencing the token should be done somewhere that doesn't block people from running the project  

Let me know what you think.

**Comment by matiasperrone** [comment]
1. **~**: I don't know what you mean with that, but, is resolved in vue config file, so they are resolved.
2. **NPM:** You may have an old version of npm because I have no problem at all. I am using version 6.14.8 as well as node v10.17

**Comment by superbiche** [comment]
**1**:

```js
import HotelDatePicker from 'vue-hotel-datepicker/src/components/DatePicker'

export default defineComponent({
  name: 'StepBooking',
  components: {
    // ...
    HotelDatePicker,
  },
}
```

```html
<HotelDatePicker />
```

Leads to:  

image

So, they might be resolved during development and build time, but afterwards - when the package is built - the Vue config file isn't picked up, so it's not resolved. 

---

**2**: 

```
❯ npm --version                                                                                                                                    (base) 
6.14.8
❯ node --version                                                                                                                     (base) 
v14.9.0
```

The error is not related to this, it's the fact that you *do* have a `NPM_TOKEN` environment variable set, when *I don't* (because I'm not publishing this package to NPM, unlinke you). Thus, anyone who wants to contribute to this package *must* have a `NPM_TOKEN` envvar set - even to run install, dev or build - which doesn't make sense: they shouldn't need to have one as they're doing nothing with npmjs.org.

**Comment by superbiche** [comment]
@matiasperrone can you check my answers and let me know if you agree,so we can get this one merged?
I'm working on a CSS "rewrite" (actually just adding a prefix everywhere to avoid that the `datepicker` class conflicts with other datepicker libraries) that I'd like to PR soon.
Thanks !

**Review by matiasperrone — APPROVED** [review]

**Comment by matiasperrone** [comment]
I agree, that maybe is better to use a relative to allow to change the components.

1 - But that's not the way that should be imported. You should refer as any package (for instance, using the default `vue new project` command):
image

2 - I don't have a permanent `NPM_TOKEN` variable with the key, I export the `NPM_TOKEN` variable each time that I want to publish the package for security issues. This shouldn't be an issue.

**Comment by matiasperrone** [comment]
Ready!

**Comment by superbiche** [comment]
@matiasperrone 
1. I totally agree this is not how it should be imported, but this will allow us to debug the packaged version by using either the compiled one or the src one (both using just by using them from NPM)  

2. That's weird, are you also exporting it when running a build ? Because I got errors everytime : on build, on install, all the time.
Maybe it's npm, I'll try with pnpm just in case.

Anyway, thanks for merging that one! Will PR new stuff later this week

**Pull request merged**
