### PR TITLE
Feature/re-selection previous date #201

### PR DESCRIPTION
**Pull request by cr-lgl**
#201  UX improvements related to check-in selection.

### CODE REVIEW

**Comment by matiasperrone** [comment]
Can you make the same modification for `v4.0.0-dev`?

**Comment by cr-lgl** [comment]
@matiasperrone I'm not sure, check the changes soon and talk to you again.

**Comment by matiasperrone** [comment]
I think it should be easier...

**Comment by cr-lgl** [comment]
> I think it should be easier...
Here it is😭  #227

**Pull request merged**
