### PR TITLE
Simplify dayClass method

### PR DESCRIPTION
**Pull request by guillaumebriday**
Related to https://github.com/krystalcampioni/vue-hotel-datepicker/issues/223

### CODE REVIEW

**Comment by matiasperrone** [comment]
You are a contributor now!

**Comment by matiasperrone** [comment]
Did you test this PR? with other cases rather than #223 ?

**Comment by guillaumebriday** [comment]
Yeah 🎉  didn't have time until now, I want to help to improve your package, but first I think we need to clean up a bit and add more test cases.

I will update this PR too with test.

**Comment by superbiche** [comment]
@guillaumebriday converting it to draft until you ship those test :wink:

**Comment by matiasperrone** [comment]
@guillaumebriday do you have the tests?

**Pull request closed without merging**
